version: '3'

tasks:
  run-linters:
    desc: Run ruff to check, format, and sort imports.
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .
    sources:
      - "**/*.py"
      - "pyproject.toml"
    generates:
      - "**/*.py"

  lint:check:
    desc: Run linters in "check-only" mode (useful for CI/CD pipelines).
    cmds:
      - uv run ruff check .
      - uv run ruff format --check .


  run-service:
    desc: "Run the service"
    cmds:
      - python3 -m src.bootstrap.run_service


  run-e2e-tests:
    desc: "Run scenarios for end to end tests"
    cmds:
      - python3 -m tests.e2e